import type { NullishPrimitive } from '@flex-development/json/utils/types'
import type { GridBreakpointKey } from '@system/types'
import { breakpointInfix } from '@system/utils/breakpointInfix'

/**
 * @file Implementation - genclass
 * @module utils/genclass/impl
 */

/**
 * Generates a CSS class name.
 *
 * Responsive variations can be generated by supplying a grid
 * {@param breakpoint} key other than "xs". Consult the Sass `$utilities` map
 * for a list of utility class prefixes and values.
 *
 * @param {string} prefix - Class prefix from Sass `$utilities` map
 * @param {NullishPrimitive} [value] - Breakpoint class value, e.g 5 or 'wrap'
 * @param {GridBreakpointKey} [breakpoint] - Grid breakpoint key
 * @return {string} CSS class name
 */
const genclass = (
  prefix: string,
  value?: NullishPrimitive,
  breakpoint: GridBreakpointKey = 'xs'
): string => {
  // If false, null, or undefined, return empty string
  if (!value && value !== 0) return ''

  let classes = ''
  let append = ''

  if (typeof value === 'number' || typeof value === 'string') {
    append = `-${value}`
  }

  if (append !== '-' || (typeof value === 'boolean' && value)) {
    classes = `${breakpointInfix(breakpoint)}${prefix}${append}`
  } else if (append === '-') {
    classes = `${breakpointInfix(breakpoint)}${prefix}`
  }

  return classes.trim()
}

export default genclass
