import { Form, FormOptions } from 'tinacms'

/**
 * @file Subdomain Utility Types - CMS
 * @module subdomains/cms/utils/types
 */

export type GenericToken = {
  email: string | null
  exp?: number
  iat?: number
  name: string | null
  picture?: string | null
}

/**
 * TinaCMS `GroupList` field items require a primary key and label.
 */
export type GroupListItemProps = {
  key: string
  label: string
}

export interface UseFormPlugin<FormValues> {
  /**
   * Form config generated by hook arguments.
   *
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#form-configuration
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#creating-forms
   */
  config: FormOptions<FormValues>

  /**
   * Form generated by the `useForm` hook.
   * Used to register the form with the `usePlugin` hook.
   *
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#hook-return-values
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#registering-forms
   */
  form: Form<FormValues>

  /**
   * Object containing all the data that is made editable by the form. As users
   * edit data in the form, the values in this object change.
   *
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#hook-return-values
   */
  modified: FormValues
}

export interface UseFormScreenPlugin<FormValues, ModifiedFormValues> {
  /**
   * Form config generated by hook arguments.
   *
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#form-configuration
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#creating-forms
   */
  config: FormOptions<FormValues>

  /**
   * Form generated by the `useForm` hook.
   * Used to register the form with the `useFormScreenPlugin` hook.
   *
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#hook-return-values
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#example-2-forms-as-screens
   */
  form: Form<FormValues>

  /**
   * Object containing all the data that is made editable by the form. As users
   * edit data in the form, the values in this object change.
   *
   * @see https://tinacms.org/docs/modules/cms/config/plugins/forms/#hook-return-values
   */
  modified: ModifiedFormValues
}
