import { Form, FormOptions } from 'tinacms'

/**
 * @file Subdomain Utility Types - CMS
 * @module subdomains/cms/utils/types
 */

export type GenericToken = {
  email: string | null
  exp?: number
  iat?: number
  name: string | null
  picture?: string | null
}

/**
 * TinaCMS `GroupList` field items require a primary key and label.
 */
export type GroupListItemProps = {
  key: string
  label: string
}

/**
 * Types of initial form data. Can be an object or a function to load the
 * initial form state asynchronously.
 */
export type InitialFormValues<T> = T | FormOptions<T>['loadInitialValues']
export interface UseFormPlugin<FormValues> {
  /**
   * Form config generated by hook arguments.
   *
   * @see https://tina.io/docs/plugins/forms/#form-configuration#form-configuration
   * @see https://tina.io/docs/plugins/forms/#form-configuration#creating-forms
   */
  config: FormOptions<FormValues>

  /**
   * Form generated by the `useForm` hook.
   * Used to register the form with the `usePlugin` hook.
   *
   * @see https://tina.io/docs/plugins/forms/#form-configuration#hook-return-values
   * @see https://tina.io/docs/plugins/forms/#form-configuration#registering-forms
   */
  form: Form<FormValues>

  /**
   * Object containing all the data that is made editable by the form. As users
   * edit data in the form, the values in this object change.
   *
   * @see https://tina.io/docs/plugins/forms/#form-configuration#hook-return-values
   */
  modified: FormValues
}

export interface UseFormScreenPlugin<FormValues, ModifiedFormValues> {
  /**
   * Form config generated by hook arguments.
   *
   * @see https://tina.io/docs/plugins/forms/#form-configuration#form-configuration
   * @see https://tina.io/docs/plugins/forms/#form-configuration#creating-forms
   */
  config: FormOptions<FormValues>

  /**
   * Form generated by the `useForm` hook.
   * Used to register the form with the `useFormScreenPlugin` hook.
   *
   * @see https://tina.io/docs/plugins/forms/#form-configuration#hook-return-values
   * @see https://tina.io/docs/plugins/forms/#form-configuration#example-2-forms-as-screens
   */
  form: Form<FormValues>

  /**
   * Object containing all the data that is made editable by the form. As users
   * edit data in the form, the values in this object change.
   *
   * @see https://tina.io/docs/plugins/forms/#form-configuration#hook-return-values
   */
  modified: ModifiedFormValues
}
